### PR TITLE
Add listener

### PR DESCRIPTION
**Pull request by cristeahub**
Changes onClick to addEventListener.

### CODE REVIEW

**Comment by sigvef** [comment]
s/listner/listener/

**Comment by stianjensen** [comment]
The diff doesn't match the commit message?

**Comment by cristeahub** [comment]
> s/listner/listener/

Where do you see this?

**Comment by sigvef** [comment]
image

**Comment by cristeahub** [comment]
Ping!

**Comment by cristeahub** [comment]
Ok, I'll change the title, but there's no issues with the code and the commit, right, @sigvef?

**Comment by sigvef** [comment]
needs rebase

**Comment by cristeahub** [comment]
ping

**Pull request merged**
